#!/bin/sh

[ "$(stat -c %y ~/.cache/corona  2> /dev/null| cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
	curl -s https://corona-stats.online/italy > ~/.cache/corona

grep "Italy" ~/.cache/corona |
	sed 's/\s*//g ; s/║//g; s/\x1b\[[0-9;]*m//g ; s/│/;/g ; s/▲//g' |
	awk -F';' '{print "[🔺" $4 " ☠️ " $6 "]"}'
