#!/bin/sh


curl -s 'https://app.earth2.io/graphql' \
  -H 'authority: app.earth2.io' \
  -H 'accept: application/json' \
  -H 'dnt: 1' \
  -H 'x-csrftoken: OVzx9rXRatFplq2EqDlxWwL1IcLhgSDunGLzKfnspdAjVpBMJ7Nu2cQkHxwdENLE' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: https://app.earth2.io' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://app.earth2.io/' \
  -H 'accept-language: en-US,en;q=0.9,it;q=0.8,ja;q=0.7' \
  -H 'cookie: csrftoken=OVzx9rXRatFplq2EqDlxWwL1IcLhgSDunGLzKfnspdAjVpBMJ7Nu2cQkHxwdENLE' \
  -H 'sec-gpc: 1' \
  --data-raw '{"query":"{\n                getPublicUserInfo(userId: \"6e0493ac-c735-4955-8b44-38cd66c2ae9f\") {\n                    username, picture, customPhoto, userNetworth {\n                        networth, totalTiles, spent\n                    }\n                },\n            }"}' \
  --compressed |
  	jq '.[].getPublicUserInfo.userNetworth.networth' |
		awk '{print "[💲"$1"]"}'
